# Generated by Django 6.0.1 on 2026-08-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Standart atribut nomi')),
                ('original_name', models.CharField(max_length=200, verbose_name='Asl atribut nomi')),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'Datetime')], max_length=20, verbose_name="Ma'lumot turi")),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name="O'lchov birligi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='datasource.datasource', verbose_name="Ma'lumot manbasi")),
            ],
            options={
                'verbose_name': 'Atribut',
                'verbose_name_plural': 'Atributlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_unit', models.CharField(blank=True, max_length=50, verbose_name="Asl o'lchov birligi")),
                ('language', models.CharField(default='en', max_length=30, verbose_name='Til')),
                ('nullable', models.BooleanField(default=True, verbose_name="Bo'sh qiymatga ruxsat")),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Minimal qiymat')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Maksimal qiymat')),
                ('example_value', models.CharField(blank=True, max_length=200, verbose_name='Namunaviy qiymat')),
                ('semantic_category', models.CharField(blank=True, max_length=100, verbose_name='Semantik kategoriya')),
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='attributes.attribute', verbose_name='Atribut')),
            ],
            options={
                'verbose_name': "Atribut metama'lumoti",
                'verbose_name_plural': "Atribut metama'lumotlari",
                'ordering': ['attribute'],
            },
        ),
    ]
