# Generated by Django 6.0.1 on 2026-08-01 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='System Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('organization', models.CharField(max_length=200)),
                ('system_type', models.CharField(choices=[('API', 'API'), ('DATABASE', 'Database'), ('SATELLITE', 'Satellite'), ('SENSOR', 'Sensor'), ('LABORATORY', 'Laboratory'), ('MANUAL', 'Manual')], max_length=30)),
                ('data_format', models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('GEOJSON', 'GeoJSON'), ('GEOTIFF', 'GeoTIFF')], max_length=30)),
                ('communication_protocol', models.CharField(choices=[('REST', 'REST API'), ('SOAP', 'SOAP'), ('FTP', 'FTP'), ('MQTT', 'MQTT'), ('WEBSOCKET', 'WebSocket')], max_length=30)),
                ('authentication_type', models.CharField(choices=[('NONE', 'None'), ('API_KEY', 'API Key'), ('BASIC', 'Basic Auth'), ('JWT', 'JWT'), ('OAUTH2', 'OAuth2')], default='NONE', max_length=30)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('update_frequency', models.CharField(choices=[('REALTIME', 'Real Time'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=30)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'db_table': 'systems',
                'ordering': ['name'],
            },
        ),
    ]
