# Generated by Django 6.0.1 on 2026-08-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Manba nomi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('source_type', models.CharField(choices=[('API', 'API'), ('DATABASE', 'Database'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('JSON', 'JSON'), ('XML', 'XML'), ('SATELLITE', 'Satellite'), ('SENSOR', 'Sensor'), ('MANUAL', 'Manual')], max_length=20, verbose_name='Manba turi')),
                ('endpoint', models.CharField(blank=True, max_length=500, verbose_name='Endpoint')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='systems.system', verbose_name='Tizim')),
            ],
            options={
                'verbose_name': "Ma'lumot manbasi",
                'verbose_name_plural': "Ma'lumot manbalari",
                'ordering': ['name'],
            },
        ),
    ]
